// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UltiTourneysApp.Data;

#nullable disable

namespace UltiTourneysApp.Migrations
{
    [DbContext(typeof(UltiTourneysDBContext))]
    [Migration("20230722151806_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.9");

            modelBuilder.Entity("UltiTourneysApp.Classes.Player", b =>
                {
                    b.Property<int>("playerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("teamID")
                        .HasColumnType("INTEGER");

                    b.HasKey("playerID");

                    b.HasIndex("teamID");

                    b.ToTable("Player");
                });

            modelBuilder.Entity("UltiTourneysApp.Classes.Team", b =>
                {
                    b.Property<int>("teamID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("division")
                        .HasColumnType("INTEGER");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("tournamentID")
                        .HasColumnType("INTEGER");

                    b.HasKey("teamID");

                    b.HasIndex("tournamentID");

                    b.ToTable("Team");
                });

            modelBuilder.Entity("UltiTourneysApp.Classes.Tournament", b =>
                {
                    b.Property<int>("tournamentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("city")
                        .HasColumnType("TEXT");

                    b.Property<string>("country")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("date")
                        .HasColumnType("TEXT");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("state")
                        .HasColumnType("TEXT");

                    b.HasKey("tournamentID");

                    b.ToTable("Tournament");
                });

            modelBuilder.Entity("UltiTourneysApp.Classes.Player", b =>
                {
                    b.HasOne("UltiTourneysApp.Classes.Team", null)
                        .WithMany("roster")
                        .HasForeignKey("teamID");
                });

            modelBuilder.Entity("UltiTourneysApp.Classes.Team", b =>
                {
                    b.HasOne("UltiTourneysApp.Classes.Tournament", null)
                        .WithMany("teams")
                        .HasForeignKey("tournamentID");
                });

            modelBuilder.Entity("UltiTourneysApp.Classes.Team", b =>
                {
                    b.Navigation("roster");
                });

            modelBuilder.Entity("UltiTourneysApp.Classes.Tournament", b =>
                {
                    b.Navigation("teams");
                });
#pragma warning restore 612, 618
        }
    }
}
